#ifndef CACHEHEADER_H
#define CACHEHEADER_H

#define CACHE_GET 0
#define CACHE_SET 1

#define DISTRIBUTED_MAXKEYLEN 1000
#define DISTRIBUTED_MAXDATALEN 4096
#define MAXTTL 604800
#define MAXSOBUF 8000

#endif
